# Generated by Django 2.1.7 on 2019-03-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=None, verbose_name='post date'),
        ),
    ]
