# Generated by Django 2.1.7 on 2019-03-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['date_created']},
        ),
    ]
