# Generated by Django 2.1.7 on 2019-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190310_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(max_length=200, null=True, verbose_name='writer bio'),
        ),
    ]
