# Generated by Django 2.1.7 on 2019-03-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogger_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(max_length=1200, null=True, verbose_name='writer bio'),
        ),
    ]
