# Generated by Django 2.1.7 on 2019-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190310_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
